R画图：画大裤衩
========================================================
```{r setup, include=FALSE}
opts_knit$set(upload.fun = imgur_upload) 
opts_chunk$set(fig.width=8, fig.height=8, out.extra='style="display:block; margin: auto"')

```

### 引子
话说突然想到用Ｒ画下CCAV的地标性建筑，闻名遐迩的大裤衩！

### 工具
线段
多边形来填色
会用到点
还有文本和颜色

### 实现
先用高级命令plot画出作图区域，然后就是线段，多边形和文本的天下了。后期恶搞中用到了点。

```{r dakucha,echo=FALSE,warning=FALSE}
par(mfrow=c(1,1))

  num=sample(-5:5,20,replace=T)
num2=num^2
plot(num2,type="n",xlim=c(-6,6),ylim=c(0,13),ylab=NA,xlab=NA,xaxt="n",yaxt="n")


segments(-2,0,-1,10)
segments(1,8,-1,10)
segments(1,8,2.5,10)
segments(4,0,2.5,10)
segments(-4,2,-2.5,13)

segments(1,10,-2.5,13)
segments(1,10,1,8)
segments(1,10,3,12.8)
segments(4.3,3,3,12.8)

segments(-4,2,-2,0,lty=2)
segments(4,0,4.3,3,lty=2)

#segments(-1,5,2.5,5,lty=2)
#segments(-1,2,-1,5,lty=2)
#segments(-1,2,2.5,2,lty=2)
#segments(1,2,1,5,lty=2)
#polygon(c(-1,3,3,-1,-1),c(5,5,2,2,5),col="white")

#points(1,3.5,cex=10,col="red",pch=20)
set.seed(2)
col1=sample(colors(),10)[6]
polygon(c(-4,-2.5,1,1,-1,-2,-4),c(2,13,10,8,10,0,2),col=col1)
polygon(c(1,1,3,4.3,4,2.5,1),c(8,10,12.8,3,0,10,8),col=col1)
text(5,12,"大",cex=2.5,col=colors()[463])
  text(5,10,"裤",cex=2.5,col=colors()[464])
  text(5,8,"衩",cex=2.5,col=colors()[465])
text(-5,11,expression(Sigma),cex=6,font=3,col="blue",srt=270)
```

当然，只是用平面画个粗略的形状，遗憾的是没有学过画画，不然，可以更好看些。固然不像立体的大裤衩，倒是像极了倒放的求和符号Sigma。
哈哈，有趣


